const error = {
    USERS_NOT_FOUND: 'USERS_NOT_FOUND',
    USER_ALREADY_EXIST: 'USER_ALREADY_EXIST',
    USER_NOT_FOUND: 'USER_NOT_FOUND',
    USER_POST_ERROR: 'USER_POST_ERROR',
    USER_DELETE_ERROR: 'USER_DELETE_ERROR',
    USERS_PASSWORD_ERROR: 'USERS_PASSWORD_ERROR',
    VALIDATION_ERROR_USER_NAME_REQUIRED: 'VALIDATION_ERROR_USER_NAME_REQUIRED',
    VALIDATION_ERROR_USER_NAME_STRING: 'VALIDATION_ERROR_USER_NAME_STRING',
    VALIDATION_ERROR_USER_NAME_LENGTH: 'VALIDATION_ERROR_USER_NAME_LENGTH',
    VALIDATION_ERROR_USER_NOMER_REQUIRED: 'VALIDATION_ERROR_USER_NOMER_REQUIRED',
    VALIDATION_ERROR_USER_NOMER_NUMERIC: 'VALIDATION_ERROR_USER_NOMER_NUMERIC',
    VALIDATION_ERROR_USER_NOMER_LENGTH: 'VALIDATION_ERROR_USER_NOMER_LENGTH',
    VALIDATION_ERROR_USER_ROLE_REQUIRED: 'VALIDATION_ERROR_USER_ROLE_REQUIRED',
    VALIDATION_ERROR_USER_LOGIN_REQUIRED: 'VALIDATION_ERROR_USER_LOGIN_REQUIRED',
    VALIDATION_ERROR_USER_LOGIN_LENGTH: 'VALIDATION_ERROR_USER_LOGIN_LENGTH',
    VALIDATION_ERROR_USER_LOGIN_STRING: 'VALIDATION_ERROR_USER_LOGIN_STRING',
    VALIDATION_ERROR_USER_PASSWORD_REQUIRED: 'VALIDATION_ERROR_USER_PASSWORD_REQUIRED',
    VALIDATION_ERROR_USER_PASSWORD_LENGTH: 'VALIDATION_ERROR_USER_PASSWORD_LENGTH',
    VALIDATION_ERROR_USER_PASSWORD_STRING: 'VALIDATION_ERROR_USER_PASSWORD_STRING',
    VALIDATION_ERROR_USER_ID_UUID:'VALIDATION_ERROR_USER_ID_UUID'
};

module.exports = {
    error,
};