const error = {
    USERS_NOT_FOUND: 'USERS_NOT_FOUND',
    USER_NOT_FOUND: 'USER_NOT_FOUND',
    USER_POST_ERROR: 'USER_POST_ERROR',
    USER_DELETE_ERROR: 'USER_DELETE_ERROR',
    VALIDATION_ERROR_USER_NAME_REQUIRED: 'VALIDATION_ERROR_USER_NAME_REQUIRED',
    VALIDATION_ERROR_USER_NAME_STRING: 'VALIDATION_ERROR_USER_NAME_STRING',
    VALIDATION_ERROR_USER_NAME_LENGTH: 'VALIDATION_ERROR_USER_NAME_LENGTH',
};

module.exports = {
    error,
};